name: zhao_benchmark
version: '1.0.0'
config-version: 2
profile: zhao_benchmark

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  zhao_benchmark:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
    rollups:
      +materialized: table
