version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: ev_00
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: ev_01
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: ev_02
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: ev_03
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: ev_04
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: ev_05
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: ev_06
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: ev_07
        columns:
          - name: event_id
          - name: customer_id
          - name: segment_id
          - name: m1
          - name: m2
          - name: m3
          - name: m4
          - name: m5
          - name: m6
          - name: m7
          - name: m8
          - name: m9
          - name: m10
          - name: m11
          - name: m12
      - name: cu_0
        columns:
          - name: customer_id
          - name: segment_id
          - name: a1
          - name: a2
          - name: a3
          - name: a4
          - name: a5
          - name: a6
      - name: cu_1
        columns:
          - name: customer_id
          - name: segment_id
          - name: a1
          - name: a2
          - name: a3
          - name: a4
          - name: a5
          - name: a6
      - name: cu_2
        columns:
          - name: customer_id
          - name: segment_id
          - name: a1
          - name: a2
          - name: a3
          - name: a4
          - name: a5
          - name: a6
      - name: cu_3
        columns:
          - name: customer_id
          - name: segment_id
          - name: a1
          - name: a2
          - name: a3
          - name: a4
          - name: a5
          - name: a6
